# Use a long-term support version of Node.js
FROM node:18-slim

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json first to leverage Docker cache
COPY package*.json ./

# Install dependencies
RUN npm install --production

# Copy the rest of the application code
COPY . .


# Expose the port Cloud Run expects
EXPOSE 3001


# Set PORT env variable for Node.js app
ENV PORT=3001

# Command to run the application
CMD ["node", "app.js"]
